# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hoy
email: junghoyo92@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Electrical Engineer & Software Developer
  24 year-old Korean-American, Bilingual
  3 L's of Life: Laugh, Love, Learn
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.hofficiallyours.me" # the base hostname & protocol for your site
twitter_username: HOfficiallYours
github_username:  junghoyo92

# Build settings
markdown: kramdown
